@host = http://localhost:5000

GET {{host}}/health
Accept: application/json

###

POST {{host}}/api/tenants
Content-Type: application/json

{
  "name": "Acme"
}

###

POST {{host}}/api/entities
Content-Type: application/json
X-Tenant-Id: 00000000-0000-0000-0000-000000000000

{
  "name": "customer",
  "displayName": "Customer",
  "description": null
}

###

POST {{host}}/api/entities/00000000-0000-0000-0000-000000000000/fields
Content-Type: application/json
X-Tenant-Id: 00000000-0000-0000-0000-000000000000

{
  "name": "name",
  "displayName": "Name",
  "dataType": "Text",
  "isRequired": true,
  "configuration": {
    "maxLength": 200
  }
}

###

POST {{host}}/api/entities/00000000-0000-0000-0000-000000000000/records
Content-Type: application/json
X-Tenant-Id: 00000000-0000-0000-0000-000000000000

{
  "data": {
    "name": "Ada Lovelace"
  }
}
