import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useParams } from 'react-router-dom'
import { api } from '../api'
import { EntityTabs } from '../components/EntityTabs'
import type { AggregateFunction, Metric, MetricEvaluation, MetricFormat } from '../types'
import { useEntityContext } from './useEntityContext'
import { AnalyticsFilterEditor } from '../components/AnalyticsFilterEditor'
import { JsonEditorModal, requireJsonObject } from '../components/JsonEditorModal'

export function MetricsPage({ tenantId }: { tenantId: string }) {
  const { entityId = '' } = useParams(); const context = useEntityContext(tenantId, entityId); const client = useQueryClient()
  const metrics = useQuery({ queryKey: ['metrics', tenantId, entityId], queryFn: () => api.metrics(tenantId, entityId) })
  const [jsonOpen, setJsonOpen] = useState(false)
  const [editing, setEditing] = useState<Metric>(); const [name, setName] = useState(''); const [aggregate, setAggregate] = useState<AggregateFunction>('Count'); const [fieldId, setFieldId] = useState(''); const [filter, setFilter] = useState<unknown>(); const [formatStyle, setFormatStyle] = useState<NonNullable<MetricFormat['style']>>('integer'); const [decimalPlaces, setDecimalPlaces] = useState(2); const [currencyCode, setCurrencyCode] = useState('USD'); const [values, setValues] = useState<Record<string, MetricEvaluation>>({})
  const save = useMutation({ mutationFn: () => api.saveMetric(tenantId, entityId, { name, aggregate, fieldId: aggregate === 'Count' ? undefined : fieldId, filter, format: { style: formatStyle, decimalPlaces, currencyCode: formatStyle === 'currency' ? currencyCode : undefined } }, editing?.id), onSuccess: () => { setEditing(undefined); setName(''); setFilter(undefined); client.invalidateQueries({ queryKey: ['metrics', tenantId, entityId] }) } })
  const remove = useMutation({ mutationFn: api.deleteMetric.bind(null, tenantId, entityId), onSuccess: () => client.invalidateQueries({ queryKey: ['metrics', tenantId, entityId] }) })
  async function evaluate(metric: Metric) { const result = await api.evaluateMetric(tenantId, entityId, metric.id); setValues(current => ({ ...current, [metric.id]: result })) }
  function edit(metric: Metric) { setEditing(metric); setName(metric.name); setAggregate(metric.aggregate); setFieldId(metric.fieldId ?? ''); setFilter(metric.filter); setFormatStyle(metric.format?.style ?? 'integer'); setDecimalPlaces(metric.format?.decimalPlaces ?? 2); setCurrencyCode(metric.format?.currencyCode ?? 'USD') }
  async function saveJson(value: unknown) { const input = requireJsonObject(value, { name: 'string', aggregate: 'string' }); const saved = await api.saveMetric(tenantId, entityId, input as unknown as Omit<Metric, 'id' | 'entityId' | 'createdAt' | 'updatedAt'>, editing?.id); edit(saved); await client.invalidateQueries({ queryKey: ['metrics', tenantId, entityId] }) }
  if (context.isLoading) return <p>Loading…</p>
  return <section className="page"><header><div><p className="eyebrow">Reusable metrics</p><h2>{context.entity?.displayName}</h2></div></header><EntityTabs entityId={entityId} />
    <div className="workspace-grid"><div className="panel"><h3>{editing ? 'Edit metric' : 'New metric'}</h3><div className="designer"><label className="field">Name<input value={name} onChange={event => setName(event.target.value)} /></label><label className="field">Aggregate<select value={aggregate} onChange={event => setAggregate(event.target.value as AggregateFunction)}><option>Count</option><option>CountDistinct</option><option>Sum</option><option>Average</option><option>Min</option><option>Max</option></select></label><label className="field">Field<select disabled={aggregate === 'Count'} value={fieldId} onChange={event => setFieldId(event.target.value)}><option value="">Select a field</option>{context.fields.map(field => <option key={field.id} value={field.id}>{field.displayName}</option>)}</select></label><AnalyticsFilterEditor fields={context.fields} value={filter} onChange={setFilter} /><div className="threshold-row"><label className="field">Format<select value={formatStyle} onChange={event => setFormatStyle(event.target.value as NonNullable<MetricFormat['style']>)}><option value="integer">Integer</option><option value="decimal">Decimal</option><option value="percentage">Percentage</option><option value="currency">Currency</option><option value="duration">Duration</option></select></label><label className="field">Decimal places<input type="number" min="0" max="10" value={decimalPlaces} onChange={event => setDecimalPlaces(Number(event.target.value))} /></label></div>{formatStyle === 'currency' && <label className="field">Currency code<input maxLength={3} value={currencyCode} onChange={event => setCurrencyCode(event.target.value.toUpperCase())} /></label>}<div className="actions"><button disabled={!name || (aggregate !== 'Count' && !fieldId)} onClick={() => save.mutate()}>Save metric</button><button className="secondary" onClick={() => setJsonOpen(true)}>Edit JSON</button>{editing && <button className="secondary" onClick={() => setEditing(undefined)}>Cancel</button>}</div>{save.error && <p className="error">{save.error.message}</p>}</div></div>
      <div className="panel wide"><h3>Metric cards</h3><div className="metric-cards">{metrics.data?.map(metric => <article className="metric-card" key={metric.id}><small>{metric.name}</small><strong>{values[metric.id] ? formatMetric(values[metric.id].value, metric) : '—'}</strong><span>{values[metric.id] ? `Updated ${new Date(values[metric.id].evaluatedAt).toLocaleTimeString()}` : `${metric.aggregate}${metric.fieldId ? ` · ${context.fields.find(field => field.id === metric.fieldId)?.displayName}` : ''}`}</span><div className="actions"><button className="secondary" onClick={() => evaluate(metric)}>Refresh</button><button className="link" onClick={() => edit(metric)}>Edit</button><button className="link danger" onClick={() => remove.mutate(metric.id)}>Delete</button></div></article>)}</div></div></div>
    {jsonOpen && <JsonEditorModal title={`${editing ? 'Edit' : 'Create'} metric as JSON`} value={{ name, aggregate, fieldId: aggregate === 'Count' ? undefined : fieldId, filter, format: { style: formatStyle, decimalPlaces, currencyCode: formatStyle === 'currency' ? currencyCode : undefined } }} onClose={() => setJsonOpen(false)} onSave={saveJson} />}
  </section>
}

function formatMetric(value: unknown, metric: Metric) { const number = Number(value); const format = metric.format; if (!Number.isFinite(number)) return String(value ?? '—'); if (format?.style === 'duration') { const seconds = Math.max(0, Math.round(number)); const hours = Math.floor(seconds / 3600); const minutes = Math.floor(seconds % 3600 / 60); return `${hours}h ${minutes}m ${seconds % 60}s` } if (format?.style === 'percentage') return new Intl.NumberFormat(undefined, { style: 'percent', maximumFractionDigits: format.decimalPlaces ?? 2 }).format(number); if (format?.style === 'currency') return new Intl.NumberFormat(undefined, { style: 'currency', currency: format.currencyCode ?? 'USD', maximumFractionDigits: format.decimalPlaces ?? 2 }).format(number); return new Intl.NumberFormat(undefined, { maximumFractionDigits: format?.style === 'integer' ? 0 : format?.decimalPlaces ?? 2 }).format(number) }
