using DynamicEntity.Application.Abstractions;
using DynamicEntity.Domain.Analytics;
using DynamicEntity.Domain.Storage;
using Microsoft.Data.SqlClient;
using System.Text.Json;

namespace DynamicEntity.SqlServer.Analytics;

public sealed class SqlAlertStore(SqlServerOptions options) : IAlertStore
{
    private const string Columns = "a.Id,a.EntityId,a.MetricId,a.Name,a.ComparisonOperator,a.ThresholdJson,a.[Interval],a.Timezone,a.CooldownSeconds,a.NotifyOnRecovery,a.IsEnabled,a.LastState,a.LastEvaluatedAt,a.NextEvaluationAt,a.LeaseOwner,a.LeaseExpiresAt,a.CreatedBy,a.CreatedAt,a.UpdatedAt";
    public async Task<AlertDefinition> CreateAsync(Guid tenantId,AlertDefinition a,EntityStorageLocation s,CancellationToken t){const string sql="""
        INSERT dbo.AlertDefinitions(Id,EntityId,MetricId,Name,ComparisonOperator,ThresholdJson,[Interval],Timezone,CooldownSeconds,NotifyOnRecovery,IsEnabled,LastState,LastEvaluatedAt,NextEvaluationAt,LeaseOwner,LeaseExpiresAt,CreatedBy,CreatedAt,UpdatedAt)
        SELECT @id,@entityId,@metricId,@name,@operator,@threshold,@interval,@timezone,@cooldown,@recovery,@enabled,@state,@evaluated,@next,@owner,@lease,@createdBy,@createdAt,@updatedAt
        WHERE EXISTS(SELECT 1 FROM dbo.EntityDefinitions e JOIN dbo.MetricDefinitions m ON m.EntityId=e.Id WHERE e.TenantId=@tenantId AND e.Id=@entityId AND m.Id=@metricId);
        """;await using var c=await OpenAsync(s,t);await using var tx=(SqlTransaction)await c.BeginTransactionAsync(t);await using var cmd=new SqlCommand(sql,c,tx);Add(cmd,tenantId,a);if(await cmd.ExecuteNonQueryAsync(t)!=1)throw new InvalidOperationException("Metric ownership changed while creating alert.");await ReplaceActionsAsync(c,tx,a,t);await tx.CommitAsync(t);return a;}
    public Task<IReadOnlyList<AlertDefinition>> ListAsync(Guid tenantId,Guid entityId,EntityStorageLocation s,CancellationToken t)=>ReadManyAsync($"SELECT {Columns} FROM dbo.AlertDefinitions a JOIN dbo.EntityDefinitions e ON e.Id=a.EntityId WHERE e.TenantId=@tenantId AND a.EntityId=@entityId ORDER BY a.Name,a.Id;",tenantId,entityId,null,s,t);
    public async Task<AlertDefinition?> GetAsync(Guid tenantId,Guid entityId,Guid alertId,EntityStorageLocation s,CancellationToken t)=>(await ReadManyAsync($"SELECT {Columns} FROM dbo.AlertDefinitions a JOIN dbo.EntityDefinitions e ON e.Id=a.EntityId WHERE e.TenantId=@tenantId AND a.EntityId=@entityId AND a.Id=@id;",tenantId,entityId,alertId,s,t)).SingleOrDefault();
    public async Task<AlertDefinition?> UpdateAsync(Guid tenantId,AlertDefinition a,EntityStorageLocation s,CancellationToken t){const string sql="""
        UPDATE a SET MetricId=@metricId,Name=@name,ComparisonOperator=@operator,ThresholdJson=@threshold,[Interval]=@interval,Timezone=@timezone,CooldownSeconds=@cooldown,NotifyOnRecovery=@recovery,IsEnabled=@enabled,LastState=@state,LastEvaluatedAt=@evaluated,NextEvaluationAt=@next,LeaseOwner=@owner,LeaseExpiresAt=@lease,UpdatedAt=@updatedAt
        FROM dbo.AlertDefinitions a JOIN dbo.EntityDefinitions e ON e.Id=a.EntityId WHERE e.TenantId=@tenantId AND a.EntityId=@entityId AND a.Id=@id;
        """;await using var c=await OpenAsync(s,t);await using var tx=(SqlTransaction)await c.BeginTransactionAsync(t);await using var cmd=new SqlCommand(sql,c,tx);Add(cmd,tenantId,a);if(await cmd.ExecuteNonQueryAsync(t)!=1){await tx.RollbackAsync(t);return null;}await ReplaceActionsAsync(c,tx,a,t);await tx.CommitAsync(t);return a;}
    public async Task<bool> DeleteAsync(Guid tenantId,Guid entityId,Guid alertId,EntityStorageLocation s,CancellationToken t){const string sql="""
        IF EXISTS(SELECT 1 FROM dbo.AlertDefinitions a JOIN dbo.EntityDefinitions e ON e.Id=a.EntityId WHERE e.TenantId=@tenantId AND a.EntityId=@entityId AND a.Id=@id)
        BEGIN
          DELETE FROM dbo.AlertActions WHERE AlertId=@id;
          DELETE FROM dbo.AlertNotifications WHERE AlertId=@id;
          DELETE FROM dbo.AlertEvaluations WHERE AlertId=@id;
          DELETE FROM dbo.AlertDefinitions WHERE Id=@id;
          SELECT CAST(1 AS BIT);
        END ELSE SELECT CAST(0 AS BIT);
        """;await using var c=await OpenAsync(s,t);await using var tx=(SqlTransaction)await c.BeginTransactionAsync(t);await using var cmd=new SqlCommand(sql,c,tx);cmd.Parameters.AddWithValue("@tenantId",tenantId);cmd.Parameters.AddWithValue("@entityId",entityId);cmd.Parameters.AddWithValue("@id",alertId);var deleted=(bool)(await cmd.ExecuteScalarAsync(t))!;await tx.CommitAsync(t);return deleted;}
    public async Task<AlertDefinition?> ClaimDueAsync(Guid tenantId,string owner,DateTimeOffset now,DateTimeOffset expires,EntityStorageLocation s,CancellationToken t){var sql=$"""
        ;WITH due AS (SELECT TOP(1) a.* FROM dbo.AlertDefinitions a WITH (UPDLOCK,READPAST,ROWLOCK) JOIN dbo.EntityDefinitions e ON e.Id=a.EntityId WHERE e.TenantId=@tenantId AND a.IsEnabled=1 AND a.NextEvaluationAt<=@now AND (a.LeaseExpiresAt IS NULL OR a.LeaseExpiresAt<=@now) ORDER BY a.NextEvaluationAt,a.Id)
        UPDATE due SET LeaseOwner=@owner,LeaseExpiresAt=@expires OUTPUT {string.Join(',',Columns.Split(',').Select(x=>"inserted."+x[(x.IndexOf('.')+1)..]))};
        """;await using var c=await OpenAsync(s,t);AlertDefinition? alert;await using(var cmd=new SqlCommand(sql,c)){cmd.Parameters.AddWithValue("@tenantId",tenantId);cmd.Parameters.AddWithValue("@owner",owner);cmd.Parameters.AddWithValue("@now",now);cmd.Parameters.AddWithValue("@expires",expires);await using var r=await cmd.ExecuteReaderAsync(t);alert=await r.ReadAsync(t)?Read(r):null;}return alert is null?null:alert with{Actions=await ReadActionsAsync(c,tenantId,alert.Id,t)};}
    public async Task CompleteAsync(Guid tenantId,AlertDefinition a,EntityStorageLocation s,CancellationToken t){const string sql="UPDATE a SET LastState=@state,LastEvaluatedAt=@evaluated,NextEvaluationAt=@next,LeaseOwner=NULL,LeaseExpiresAt=NULL,UpdatedAt=@updatedAt FROM dbo.AlertDefinitions a JOIN dbo.EntityDefinitions e ON e.Id=a.EntityId WHERE e.TenantId=@tenantId AND a.Id=@id AND a.LeaseOwner=@owner;";await using var c=await OpenAsync(s,t);await using var cmd=new SqlCommand(sql,c);Add(cmd,tenantId,a);await cmd.ExecuteNonQueryAsync(t);}
    private async Task<IReadOnlyList<AlertDefinition>> ReadManyAsync(string sql,Guid tenantId,Guid entityId,Guid? id,EntityStorageLocation s,CancellationToken t){await using var c=await OpenAsync(s,t);var result=new List<AlertDefinition>();await using(var cmd=new SqlCommand(sql,c)){cmd.Parameters.AddWithValue("@tenantId",tenantId);cmd.Parameters.AddWithValue("@entityId",entityId);if(id is not null)cmd.Parameters.AddWithValue("@id",id.Value);await using var r=await cmd.ExecuteReaderAsync(t);while(await r.ReadAsync(t))result.Add(Read(r));}for(var i=0;i<result.Count;i++)result[i]=result[i] with{Actions=await ReadActionsAsync(c,tenantId,result[i].Id,t)};return result;}
    private async Task<SqlConnection> OpenAsync(EntityStorageLocation s,CancellationToken t){if(!string.Equals(s.ConnectionKey,options.ConnectionKey,StringComparison.Ordinal))throw new InvalidOperationException("Unknown tenant connection key.");var b=new SqlConnectionStringBuilder(options.TenantServerConnectionString){InitialCatalog=s.DatabaseName};var c=new SqlConnection(b.ConnectionString);await c.OpenAsync(t);return c;}
    private static void Add(SqlCommand c,Guid tenantId,AlertDefinition a){c.Parameters.AddWithValue("@tenantId",tenantId);c.Parameters.AddWithValue("@id",a.Id);c.Parameters.AddWithValue("@entityId",a.EntityId);c.Parameters.AddWithValue("@metricId",a.MetricId);c.Parameters.AddWithValue("@name",a.Name);c.Parameters.AddWithValue("@operator",a.ComparisonOperator.ToString());c.Parameters.AddWithValue("@threshold",a.ThresholdJson);c.Parameters.AddWithValue("@interval",a.Interval.ToString());c.Parameters.AddWithValue("@timezone",a.Timezone);c.Parameters.AddWithValue("@cooldown",Convert.ToInt32(a.Cooldown.TotalSeconds));c.Parameters.AddWithValue("@recovery",a.NotifyOnRecovery);c.Parameters.AddWithValue("@enabled",a.IsEnabled);c.Parameters.AddWithValue("@state",(object?)a.LastState?.ToString()??DBNull.Value);c.Parameters.AddWithValue("@evaluated",(object?)a.LastEvaluatedAt??DBNull.Value);c.Parameters.AddWithValue("@next",a.NextEvaluationAt);c.Parameters.AddWithValue("@owner",(object?)a.LeaseOwner??DBNull.Value);c.Parameters.AddWithValue("@lease",(object?)a.LeaseExpiresAt??DBNull.Value);c.Parameters.AddWithValue("@createdBy",(object?)a.CreatedBy??DBNull.Value);c.Parameters.AddWithValue("@createdAt",a.CreatedAt);c.Parameters.AddWithValue("@updatedAt",a.UpdatedAt);}
    private static AlertDefinition Read(SqlDataReader r)=>new(r.GetGuid(0),r.GetGuid(1),r.GetGuid(2),r.GetString(3),Enum.Parse<AlertComparisonOperator>(r.GetString(4)),r.GetString(5),Enum.Parse<AlertInterval>(r.GetString(6)),r.GetString(7),TimeSpan.FromSeconds(r.GetInt32(8)),r.GetBoolean(9),r.GetBoolean(10),[],r.IsDBNull(11)?null:Enum.Parse<AlertState>(r.GetString(11)),r.IsDBNull(12)?null:r.GetFieldValue<DateTimeOffset>(12),r.GetFieldValue<DateTimeOffset>(13),r.IsDBNull(14)?null:r.GetString(14),r.IsDBNull(15)?null:r.GetFieldValue<DateTimeOffset>(15),r.IsDBNull(16)?null:r.GetGuid(16),r.GetFieldValue<DateTimeOffset>(17),r.GetFieldValue<DateTimeOffset>(18));
    private static async Task ReplaceActionsAsync(SqlConnection c,SqlTransaction tx,AlertDefinition a,CancellationToken t){await using(var delete=new SqlCommand("DELETE FROM dbo.AlertActions WHERE AlertId=@alertId;",c,tx)){delete.Parameters.AddWithValue("@alertId",a.Id);await delete.ExecuteNonQueryAsync(t);}foreach(var action in a.Actions){const string sql="INSERT dbo.AlertActions(AlertId,ActionType,EmailRecipientsJson,WebhookUrlsJson) VALUES(@alertId,@type,@emails,@urls);";await using var insert=new SqlCommand(sql,c,tx);insert.Parameters.AddWithValue("@alertId",a.Id);insert.Parameters.AddWithValue("@type",action.Type.ToString());insert.Parameters.AddWithValue("@emails",action.EmailRecipients is null?DBNull.Value:JsonSerializer.Serialize(action.EmailRecipients));insert.Parameters.AddWithValue("@urls",action.WebhookUrls is null?DBNull.Value:JsonSerializer.Serialize(action.WebhookUrls));await insert.ExecuteNonQueryAsync(t);}}
    private static async Task<IReadOnlyList<AlertActionConfiguration>> ReadActionsAsync(SqlConnection c,Guid tenantId,Guid alertId,CancellationToken t){const string sql="SELECT x.ActionType,x.EmailRecipientsJson,x.WebhookUrlsJson FROM dbo.AlertActions x JOIN dbo.AlertDefinitions a ON a.Id=x.AlertId JOIN dbo.EntityDefinitions e ON e.Id=a.EntityId WHERE e.TenantId=@tenantId AND x.AlertId=@alertId ORDER BY x.ActionType;";await using var cmd=new SqlCommand(sql,c);cmd.Parameters.AddWithValue("@tenantId",tenantId);cmd.Parameters.AddWithValue("@alertId",alertId);await using var r=await cmd.ExecuteReaderAsync(t);var result=new List<AlertActionConfiguration>();while(await r.ReadAsync(t))result.Add(new(Enum.Parse<AlertActionType>(r.GetString(0)),r.IsDBNull(1)?null:JsonSerializer.Deserialize<string[]>(r.GetString(1)),r.IsDBNull(2)?null:JsonSerializer.Deserialize<Uri[]>(r.GetString(2))));return result;}
}

public sealed class SqlAlertEvaluationStore(SqlServerOptions options):IAlertEvaluationStore
{
    public async Task CreateAsync(Guid tenantId,AlertEvaluation e,EntityStorageLocation s,CancellationToken t){const string sql="INSERT dbo.AlertEvaluations(Id,AlertId,ValueJson,ThresholdJson,State,Error,EvaluatedAt) SELECT @id,@alert,@value,@threshold,@state,@error,@at WHERE EXISTS(SELECT 1 FROM dbo.AlertDefinitions a JOIN dbo.EntityDefinitions d ON d.Id=a.EntityId WHERE a.Id=@alert AND d.TenantId=@tenant);";await using var c=await SqlAlertStoreHelpers.OpenAsync(options,s,t);await using var cmd=new SqlCommand(sql,c);Add(cmd,tenantId,e);await cmd.ExecuteNonQueryAsync(t);}
    public async Task<IReadOnlyList<AlertEvaluation>> ListAsync(Guid tenantId,Guid alertId,EntityStorageLocation s,CancellationToken t){const string sql="SELECT TOP(200) v.Id,v.AlertId,v.ValueJson,v.ThresholdJson,v.State,v.Error,v.EvaluatedAt FROM dbo.AlertEvaluations v JOIN dbo.AlertDefinitions a ON a.Id=v.AlertId JOIN dbo.EntityDefinitions e ON e.Id=a.EntityId WHERE e.TenantId=@tenant AND v.AlertId=@alert ORDER BY v.EvaluatedAt DESC;";await using var c=await SqlAlertStoreHelpers.OpenAsync(options,s,t);await using var cmd=new SqlCommand(sql,c);cmd.Parameters.AddWithValue("@tenant",tenantId);cmd.Parameters.AddWithValue("@alert",alertId);await using var r=await cmd.ExecuteReaderAsync(t);var x=new List<AlertEvaluation>();while(await r.ReadAsync(t))x.Add(new(r.GetGuid(0),r.GetGuid(1),r.IsDBNull(2)?null:r.GetString(2),r.GetString(3),Enum.Parse<AlertState>(r.GetString(4)),r.IsDBNull(5)?null:r.GetString(5),r.GetFieldValue<DateTimeOffset>(6)));return x;}
    private static void Add(SqlCommand c,Guid tenantId,AlertEvaluation e){c.Parameters.AddWithValue("@tenant",tenantId);c.Parameters.AddWithValue("@id",e.Id);c.Parameters.AddWithValue("@alert",e.AlertId);c.Parameters.AddWithValue("@value",(object?)e.ValueJson??DBNull.Value);c.Parameters.AddWithValue("@threshold",e.ThresholdJson);c.Parameters.AddWithValue("@state",e.State.ToString());c.Parameters.AddWithValue("@error",(object?)e.Error??DBNull.Value);c.Parameters.AddWithValue("@at",e.EvaluatedAt);}
}

public sealed class SqlAlertNotificationStore(SqlServerOptions options):IAlertNotificationStore
{
    public async Task CreateAsync(Guid tenantId,AlertNotification n,EntityStorageLocation s,CancellationToken t){const string sql="INSERT dbo.AlertNotifications(Id,AlertId,EvaluationId,Channel,Status,Attempts,LastError,CreatedAt,DeliveredAt) SELECT @id,@alert,@evaluation,@channel,@status,@attempts,@error,@created,@delivered WHERE EXISTS(SELECT 1 FROM dbo.AlertDefinitions a JOIN dbo.EntityDefinitions e ON e.Id=a.EntityId WHERE a.Id=@alert AND e.TenantId=@tenant);";await using var c=await SqlAlertStoreHelpers.OpenAsync(options,s,t);await using var cmd=new SqlCommand(sql,c);Add(cmd,tenantId,n);try{await cmd.ExecuteNonQueryAsync(t);}catch(SqlException ex)when(ex.Number is 2601 or 2627){}}
    public async Task<IReadOnlyList<AlertNotification>> ListAsync(Guid tenantId,Guid alertId,EntityStorageLocation s,CancellationToken t){const string sql="SELECT TOP(200) n.Id,n.AlertId,n.EvaluationId,n.Channel,n.Status,n.Attempts,n.LastError,n.CreatedAt,n.DeliveredAt FROM dbo.AlertNotifications n JOIN dbo.AlertDefinitions a ON a.Id=n.AlertId JOIN dbo.EntityDefinitions e ON e.Id=a.EntityId WHERE e.TenantId=@tenant AND n.AlertId=@alert ORDER BY n.CreatedAt DESC;";await using var c=await SqlAlertStoreHelpers.OpenAsync(options,s,t);await using var cmd=new SqlCommand(sql,c);cmd.Parameters.AddWithValue("@tenant",tenantId);cmd.Parameters.AddWithValue("@alert",alertId);await using var r=await cmd.ExecuteReaderAsync(t);var x=new List<AlertNotification>();while(await r.ReadAsync(t))x.Add(new(r.GetGuid(0),r.GetGuid(1),r.GetGuid(2),r.GetString(3),Enum.Parse<NotificationStatus>(r.GetString(4)),r.GetInt32(5),r.IsDBNull(6)?null:r.GetString(6),r.GetFieldValue<DateTimeOffset>(7),r.IsDBNull(8)?null:r.GetFieldValue<DateTimeOffset>(8)));return x;}
    private static void Add(SqlCommand c,Guid tenantId,AlertNotification n){c.Parameters.AddWithValue("@tenant",tenantId);c.Parameters.AddWithValue("@id",n.Id);c.Parameters.AddWithValue("@alert",n.AlertId);c.Parameters.AddWithValue("@evaluation",n.EvaluationId);c.Parameters.AddWithValue("@channel",n.Channel);c.Parameters.AddWithValue("@status",n.Status.ToString());c.Parameters.AddWithValue("@attempts",n.Attempts);c.Parameters.AddWithValue("@error",(object?)n.LastError??DBNull.Value);c.Parameters.AddWithValue("@created",n.CreatedAt);c.Parameters.AddWithValue("@delivered",(object?)n.DeliveredAt??DBNull.Value);}
}

internal static class SqlAlertStoreHelpers{public static async Task<SqlConnection> OpenAsync(SqlServerOptions o,EntityStorageLocation s,CancellationToken t){if(!string.Equals(s.ConnectionKey,o.ConnectionKey,StringComparison.Ordinal))throw new InvalidOperationException("Unknown tenant connection key.");var b=new SqlConnectionStringBuilder(o.TenantServerConnectionString){InitialCatalog=s.DatabaseName};var c=new SqlConnection(b.ConnectionString);await c.OpenAsync(t);return c;}}
